version: "3.7"
services:
  postgres:
    container_name: zep-postgres
    restart: on-failure
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres